version: "3.3"
services:
  postgres:
    container_name: lappis
    environment:
      - POSTGRES_USER=lappis
      - POSTGRES_PASSWORD=lappis
      - POSTGRES_DB=lappis
    ports:
      - "5432:5432"
    image: postgres
